import { Sizes } from 'src/app/shared/model/size-clothe.model';

export var sizes: Sizes [] = [
    { type: 'Maglia', value: 'XXS', gender: 'M'},
    { type: 'Maglia', value: 'XXS', gender: 'F'},
    { type: 'Maglia', value: 'XS', gender: 'M'},
    { type: 'Maglia', value: 'XS', gender: 'F'},
    { type: 'Maglia', value: 'S', gender: 'M'},
    { type: 'Maglia', value: 'S', gender: 'F'},
    { type: 'Maglia', value: 'M', gender: 'M'},
    { type: 'Maglia', value: 'M', gender: 'F'},
    { type: 'Maglia', value: 'L', gender: 'M'},
    { type: 'Maglia', value: 'L', gender: 'F'},
    { type: 'Maglia', value: 'XL', gender: 'M'},
    { type: 'Maglia', value: 'XL', gender: 'F'},
    { type: 'Maglia', value: 'XXL', gender: 'M'},
    { type: 'Maglia', value: 'XXL', gender: 'F'},

    { type: 'Pantaloni', value: 34, gender: 'F'},
    { type: 'Pantaloni', value: 36, gender: 'F'},
    { type: 'Pantaloni', value: 38, gender: 'F'},
    { type: 'Pantaloni', value: 40, gender: 'F'},
    { type: 'Pantaloni', value: 42, gender: 'F'},
    { type: 'Pantaloni', value: 44, gender: 'F'},
    { type: 'Pantaloni', value: 46, gender: 'F'},
    { type: 'Pantaloni', value: 48, gender: 'F'},
    { type: 'Pantaloni', value: 50, gender: 'F'},
    { type: 'Pantaloni', value: 52, gender: 'F'},
    { type: 'Pantaloni', value: 54, gender: 'F'},

    { type: 'Pantaloni', value: 40, gender: 'M'},
    { type: 'Pantaloni', value: 42, gender: 'M'},
    { type: 'Pantaloni', value: 44, gender: 'M'},
    { type: 'Pantaloni', value: 46, gender: 'M'},
    { type: 'Pantaloni', value: 48, gender: 'M'},
    { type: 'Pantaloni', value: 50, gender: 'M'},
    { type: 'Pantaloni', value: 52, gender: 'M'},
    { type: 'Pantaloni', value: 54, gender: 'M'},
    { type: 'Pantaloni', value: 56, gender: 'M'},
    { type: 'Pantaloni', value: 58, gender: 'M'},

    { type: 'Scarpe', value: 36, gender: 'F'},
    { type: 'Scarpe', value: 37, gender: 'F'},
    { type: 'Scarpe', value: 38, gender: 'F'},
    { type: 'Scarpe', value: 39, gender: 'F'},
    { type: 'Scarpe', value: 40, gender: 'F'},
    { type: 'Scarpe', value: 41, gender: 'F'},
    { type: 'Scarpe', value: 42, gender: 'F'},
    { type: 'Scarpe', value: 43, gender: 'F'},

    { type: 'Scarpe', value: 38, gender: 'M'},
    { type: 'Scarpe', value: 39, gender: 'M'},
    { type: 'Scarpe', value: 40, gender: 'M'},
    { type: 'Scarpe', value: 41, gender: 'M'},
    { type: 'Scarpe', value: 42, gender: 'M'},
    { type: 'Scarpe', value: 43, gender: 'M'},
    { type: 'Scarpe', value: 44, gender: 'M'},
    { type: 'Scarpe', value: 45, gender: 'M'},
    { type: 'Scarpe', value: 46, gender: 'M'},
    { type: 'Scarpe', value: 47, gender: 'M'},
    { type: 'Scarpe', value: 48, gender: 'M'}

]