name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: behe/heroku-build@v1
        with:
          app-name: "backoffice-ronda"
          api-key: "020a2078-f9b5-4065-b6a2-a6f48814212b"
          path: "./back-office"
